# -*- coding: utf-8 -*-
"""Clase 1. variables y operadores aritméticos CLASE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TuvlKsAQ61hSH4GkL4Oo48E2DPNb2F3

## **1.2. Interpretación de código**
"""

# Ejemplo 1.1.1
a = 5
b = 3
c = a + b
print (c)

# Ejemplo 1.1.2
x = "5"
y = "2"
print(x + y)

# Ejemplo 1.1.3
palabra = "hola"
print(palabra * 3)

# Ejemplo 1.1.4
palabra = "Tema"
print(palabra + str(1))
print(palabra,str(1))
print(palabra+" "+str(1))
print(f"{palabra} {str(1)}")

# Ejemplo 1.1.5
resultado = 7 / 2
print(resultado)
print(type(resultado))

# Ejemplo 1.1.6
#numero = int("5.0")
numero = int(float("5.0"))
print(numero)

# Ejemplo 1.1.7
x = 10
y = 5
print(x > y)

# Ejemplo 1.1.8
x = True
print(x + 3)

# Ejemoplo 1.1.9
a = b = c = 1
a = 5
print(a, b, c)

"""## **1.3. Ejercicios prácticos de exploración**"""

'''
1.3.1.
Pide al usuario el total de una cuenta y el porcentaje de propina (por ejemplo, 10%, 15%, 20%).
Calcula y muestra en pantalla el total a pagar.
'''

'''
1.3.2.
Solicita al usuario su nombre completo (asume dos nombres y dos apellidos).
Luego, el programa generará, su correo con el formato:
primer_nombre.primer_apellido@keyinstitute.edu.sv
'''

"""## **1.4.¡Desafíos de ingenio!**"""

'''
1.4.1.
Dados tres enteros a, b y k, imprime el resultado de a / b con k decimales exactos (sin redondear).
'''

'''
1.4.2.
Dados dos números enteros positivos muy grandes como cadenas de texto A y B.
Calcula (A + B) e imprímelo como cadena de texto.
'''

'''
1.4.3.
Dado un arreglo de n fracciones (representadas como cadenas "a/b"),
calcula la suma total y expresa el resultado como una fracción irreducible.
'''